apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox
  name: bbox
spec:
  containers:
  - image: busybox:1.35.0
    name: bbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
