---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "11.6.27"        # specify version or version range
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
